1706277504.474588 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:91 __init__ INFO: Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    executors=(ThreadPoolExecutor(
        label='threads', 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    ),), 
    garbage_collect=True, 
    initialize_logging=True, 
    internal_tasks_max_threads=10, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    retry_handler=None, 
    run_dir='runinfo', 
    strategy='simple', 
    usage_tracking=False
)
1706277504.474928 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:93 __init__ INFO: Parsl version: 2024.01.22
1706277504.475070 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.usage_tracking.usage:127 __init__ DEBUG: Tracking status: False
1706277504.475233 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:121 __init__ INFO: Run id is: f80de4a2-45a5-4fe0-a2fa-203f4a421ece
1706277504.522966 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/brenddon/.local/lib/python3.12/site-packages/parsl/dataflow/dflow.py
1706277504.523102 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/brenddon/.local/lib/python3.12/site-packages/typeguard/__init__.py
1706277504.523164 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/brenddon/.local/lib/python3.12/site-packages/parsl/dataflow/dflow.py
1706277504.523215 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/brenddon/.local/lib/python3.12/site-packages/typeguard/__init__.py
1706277504.523261 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:128 __init__ DEBUG: Considering candidate for workflow name: /home/brenddon/Documents/lncc/programaDeVerao2024/parte2/workflowsPythonParsl/conteudo/00-Hello/00_hello_parsl.py
1706277504.523304 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:134 __init__ DEBUG: Using 00_hello_parsl.py as workflow name
1706277504.523538 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.memoization:163 __init__ INFO: App caching initialized
1706277504.523623 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.jobs.strategy:143 __init__ DEBUG: Scaling strategy: simple
1706277504.527733 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:949 submit DEBUG: Task 0 will be sent to executor threads
1706277504.528034 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:764 _add_output_deps DEBUG: Adding output dependencies
1706277504.528160 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1031 submit INFO: Task 0 submitted for App double, not waiting on any dependency
1706277504.528259 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1037 submit DEBUG: Task 0 set to pending state with AppFuture: <AppFuture at 0x7ff2471fb680 state=pending>
1706277504.528344 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.memoization:222 check_memo DEBUG: Task 0 will not be memoized
1706277504.529245 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:727 launch_task INFO: Parsl task 0 try 0 launched on executor threads
1706277504.529596 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.app.errors:118 reraise DEBUG: Reraising exception of type <class 'NameError'>
1706277504.530261 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:305 handle_exec_update DEBUG: Task 0 try 0 failed
1706277504.530639 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:351 handle_exec_update ERROR: Task 0 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/brenddon/.local/lib/python3.12/site-packages/parsl/dataflow/dflow.py", line 302, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brenddon/.local/lib/python3.12/site-packages/parsl/dataflow/dflow.py", line 572, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/brenddon/.local/lib/python3.12/site-packages/parsl/app/errors.py", line 122, in reraise
    reraise(t, v, v.__traceback__)
  File "/usr/lib/python3.12/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/brenddon/.local/lib/python3.12/site-packages/parsl/app/errors.py", line 145, in wrapper
    return func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/brenddon/Documents/lncc/programaDeVerao2024/parte2/workflowsPythonParsl/conteudo/00-Hello/00_hello_parsl.py", line 11, in double
    aaa
      ^^
NameError: name 'aaa' is not defined
1706277504.567622 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1145 atexit_cleanup INFO: DFK cleanup because python process is exiting
1706277504.567787 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1182 cleanup INFO: DFK cleanup initiated
1706277504.567864 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1075 log_task_states INFO: Summary of tasks in DFK:
1706277504.567945 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.unsched: 0
1706277504.568014 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.pending: 0
1706277504.568084 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.running: 0
1706277504.568151 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.exec_done: 0
1706277504.568215 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.failed: 1
1706277504.568276 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.dep_fail: 0
1706277504.568338 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.launched: 0
1706277504.568400 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.fail_retryable: 0
1706277504.568465 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.memo_done: 0
1706277504.568527 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.joining: 0
1706277504.568589 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1079 log_task_states INFO: Tasks in state States.running_ended: 0
1706277504.568654 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1081 log_task_states INFO: End of summary
1706277504.568802 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1206 cleanup INFO: Closing job status poller
1706277504.569020 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1208 cleanup INFO: Terminated job status poller
1706277504.569103 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1210 cleanup INFO: Scaling in and shutting down executors
1706277504.569202 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1228 cleanup INFO: Shutting down executor threads
1706277504.569272 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.executors.threads:74 shutdown DEBUG: Shutting down executor, which involves waiting for running tasks to complete
1706277504.569341 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.executors.threads:76 shutdown DEBUG: Done with executor shutdown
1706277504.569399 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1230 cleanup INFO: Shut down executor threads
1706277504.569459 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1228 cleanup INFO: Shutting down executor _parsl_internal
1706277504.569515 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.executors.threads:74 shutdown DEBUG: Shutting down executor, which involves waiting for running tasks to complete
1706277504.569574 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.executors.threads:76 shutdown DEBUG: Done with executor shutdown
1706277504.569631 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1230 cleanup INFO: Shut down executor _parsl_internal
1706277504.569755 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1232 cleanup INFO: Terminated executors
1706277504.569833 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.dataflow.dflow:1249 cleanup INFO: DFK cleanup complete
1706277504.569904 2024-01-26 10:58:24 MainProcess-7819 MainThread-140678588897088 parsl.process_loggers:28 wrapped DEBUG: Normal ending for cleanup on thread MainThread
